# Generated by Django 3.1.3 on 2023-01-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230121_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='folllow_id',
            new_name='follow_id',
        ),
    ]
